name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_CORS_PROXY_URL: https://sudo-proxy-1.onrender.com
      VITE_TMDB_READ_API_KEY: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1MDZiYjRjOTQ3Mzg0OTY0OWYxNmEzZjdkMzdmMzdhYSIsIm5iZiI6MTY5ODY3MTUzMi44NTQsInN1YiI6IjY1M2ZhYmFjYmMyY2IzMDBjOTdmYjdkMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.QLsJXOorj6xcvIg5GWfLqW_fLffZmsADBT3TxPEm2HA

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
